version: "3"

services:
    proxy:
        build:
            context: .
            dockerfile: docker/proxy/Dockerfile
        networks:
            default:
                ipv4_address: 172.18.0.12
        volumes:
            - /dev/log:/dev/log
        ports:
            - "443:443"
            - "80:80"
            - "9999:9999"
        privileged: true
    filter:
        build:
            context: .
            dockerfile: docker/filter/Dockerfile
        networks:
            default:
                ipv4_address: 172.18.0.13         
        ports:
            - "8081:8081"
    revproxy:
        build:
            context: .
            dockerfile: docker/revproxy/Dockerfile
        networks:
            default:
                ipv4_address: 172.18.0.14         
        ports:
            - "8082:8082"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24              
